### PR TITLE
Refactor controller

### PR DESCRIPTION
**Pull request by shimastripe**
## WHAT
- Refactor the flow of `if` statement
    - controller:`pretty`, `pagination`
    - pagination: `c.Request.TLS`
- Insert lines and Adjust the position in each logic statement.

In order to avoid mistakes, I make this branch based on #92 branch.
After #92 , I rebase this branch to the master of that time. Sorry 🙇

### CODE REVIEW

**Comment by dtan4** [comment]
plz attach `[DO NOT MERGE]` prefix in title, if this pull request is not ready to merge into master.

**Comment by shimastripe** [comment]
I'll be careful. Thank you very much. 🙏

**Comment by dtan4** [comment]
#92 has been merged. Please do merge / rebase 🙏

**Comment by shimastripe** [comment]
merged. plz check! 🙇

**Comment by dtan4** [comment]
LGTM 👍

**Pull request merged**
