### PR TITLE
Generate API Blueprint (retry)

### LINKED ISSUE #12: Generate documents in API Blueprint
## WHY
To understand the specification of genereted APIs, we have to prepare the documents.

## WHAT
Generate documents with programs.

[API Blueprint](https://apiblueprint.org/) is better format of API documents. This format is easy to read and edit because this is based on Markdown. Also, HTML document and API tests are generated easily by using other tools.

Directory structure is below:

```
|-- docs
    |-- index.apib
    |-- user.apib
    `-- profile.apib
```

API Blueprint documents are generated inside `docs` directory. `index.apib` is the top page of documents and has the links to each API pages.

### Multiple files
Currently there is no specification of multiple (modulized) files in API Blueprint. There are some solutions by using document generators.

We are going to user [aglio](https://github.com/danielgtaylor/aglio) for document generator. Therefore the links to other document should be written as below:

```
# Gist Fox API

# Group Gist

<!-- include(blueprint/gist.apib) -->

<!-- include(blueprint/gists.apib) -->
```

## REF
- [Working with multiple API Blueprint files](https://gist.github.com/zdne/5f8295642af18aff27ec)

### PR DESCRIPTION
**Pull request by dtan4**
Close #12 

## WHY
We would like to generate complete API documents automatically.

Now #14 branch is so different from master. Therefore I decided to rewrite this feature from scratch rather than rebasing #14.

## WHAT
Implemented a feature to generate documents in API Blueprint.

Documents are generated in `docs` directory, like below:

```
|-- docs
    |-- index.apib
    |-- user.apib
    `-- profile.apib
```

`index.apib` is the main page of entire document. `index.apib` has references to other pages, so finally all documents are shown in one page.

image

### CODE REVIEW

**Comment by shimastripe** [comment]
:eyes:

**Comment by shimastripe** [comment]
## Relationship model

```
# Data Structures
## accountnames (object)

+ id: 1 (number)
+ user_id: 1 (number)
+ user (users)
+ account_name: ACCOUNTNAME (string)
```

In the above code, relationship model were able successfully generated.

But, Dredd(testing tool) need single apib file, so finally when we use Dredd, we need to combine all files to single file...

**Comment by dtan4** [comment]
Maybe the implementation of relationships #21 .

**Comment by shimastripe** [comment]
```
    + Attributes

        + name: NAME  (string)
        + user ()
        + nation ()
        + nation_id: 1  (number)
```

blank  structure name

```
+ user (users)
+ nation (nations)
```

**Comment by shimastripe** [comment]
I have two requests.

## Accept-Header

Please add Accept-Header.

```
## users [/users]

+ Headers

        Accept: application/vnd.{{ .User }}+json

...

## user details [/users/{id}]

+ Headers

        Accept: application/vnd.{{ .User }}+json
```

## fixed option

Please put with the fixed option to attribute under all of the response.

Ex.
```
+ Response 200 (application/json; charset=utf-8)
    + Attributes (users, fixed)
```

**Comment by shimastripe** [comment]
## Accept-Header

Sorry this error occured.

> the 'headers' section at this level is deprecated and will be removed in a future, use respective payload header section(s) instead

So please put in this position.

```
+ Request users (application/json; charset=utf-8)
    + Headers

            Accept: application/vnd.wantedly+json

    + Attributes
        + profile_id: 1 (number)

+ Response 201 (application/json; charset=utf-8)
    + Headers

            Accept: application/vnd.wantedly+json

    + Attributes (users)
```

**Comment by dtan4** [comment]
- [x] Include associated model name
- [x] Include Accept header example

We have to discuss whether combining API Blueprint files or not.

**Comment by shimastripe** [comment]
From the point of view of readability, I think that there is no problem remains basically split.

Try a little more thought an effective method of testing with Dread.
Sorry not put out distinct answer...

**Comment by dtan4** [comment]
Thank you @shimastripe , I think so too. I wish API Blueprint supported multiple files officially...

Let's discuss next Tuesday.

**Comment by dtan4** [comment]
Now most of API Blueprint features are implemented. It's time to merge.

**Pull request merged**
