### PR TITLE
Parallel generate file

### PR DESCRIPTION
**Pull request by munisystem**
## WHY
To improve processing performance.

## WHAT
- `new` and `gen` subcommand generate file parallel.
- Remove hardcode template file name.

### CODE REVIEW

**Comment by dtan4** [comment]
`new` command generates all files at the application root. Plz fix this.

```
$ ls
#version.go#    db.go           main.go         router.go       set_db.go       version_test.go
README.md       field.go        pagination.go   server.go       version.go
```

(`#version.go` is a backup file by Emacs)

**Comment by dtan4** [comment]
Sometimes `gen` command fails due to concurrent map write / read.
panic log: https://gist.github.com/dtan4/98b38981d36a213bf5f2fd6ec74d4c2d

Probably there are some non-thread-safe points. Please take a look.

**Comment by munisystem** [comment]
>As always, if one goroutine is writing to a map, no other goroutine should be reading or writing the map concurrently.
https://blog.golang.org/go1.6

😄  ...FIx it.

**Comment by munisystem** [comment]
Fixed.

## generated path
```
>>> bin/apig new hoge
	create /Users/muni/.go/src/github.com/munisystem/hoge/.gitignore
	create /Users/muni/.go/src/github.com/munisystem/hoge/router/router.go
	create /Users/muni/.go/src/github.com/munisystem/hoge/helper/field.go
	create /Users/muni/.go/src/github.com/munisystem/hoge/server/server.go
	create /Users/muni/.go/src/github.com/munisystem/hoge/controllers/.gitkeep
	create /Users/muni/.go/src/github.com/munisystem/hoge/models/.gitkeep
	create /Users/muni/.go/src/github.com/munisystem/hoge/version/version.go
	create /Users/muni/.go/src/github.com/munisystem/hoge/db/db.go
	create /Users/muni/.go/src/github.com/munisystem/hoge/middleware/set_db.go
	create /Users/muni/.go/src/github.com/munisystem/hoge/docs/.gitkeep
	create /Users/muni/.go/src/github.com/munisystem/hoge/main.go
	create /Users/muni/.go/src/github.com/munisystem/hoge/version/version_test.go
	create /Users/muni/.go/src/github.com/munisystem/hoge/README.md
	create /Users/muni/.go/src/github.com/munisystem/hoge/db/pagination.go
===> Created /Users/muni/.go/src/github.com/munisystem/hoge

>>> ls $GOPATH/src/github.com/munisystem/hogee
README.md   db          helper      middleware  router      version
controllers docs        main.go     models      server
```

## Concurrent R/W map (golang v1.6)
```
>>> go version
go version go1.6.2 darwin/amd64
>>> make
go get github.com/jteeuwen/go-bindata/...
./glide install
[WARN]	The name listed in the config file (github.com/wantedly/apig) does not match the current location (.)
[INFO]	Downloading dependencies. Please wait...
[INFO]	--> Found desired version github.com/gedex/inflector 91797f1712fd58f224781be1080b8613d096187e!
[INFO]	--> Found desired version github.com/tcnksm/go-gitconfig 6411ba19847f20afe47f603328d97aaeca6def6f!
[INFO]	Setting references.
[INFO]	--> Setting version for github.com/gedex/inflector to 91797f1712fd58f224781be1080b8613d096187e.
[INFO]	--> Setting version for github.com/tcnksm/go-gitconfig to 6411ba19847f20afe47f603328d97aaeca6def6f.
go generate
go build -ldflags="-s -w" -o bin/apig

>>> ./apig gen
	create /Users/muni/.go/src/github.com/munisystem/hoge/docs/nation.apib
	create /Users/muni/.go/src/github.com/munisystem/hoge/docs/user.apib
	create /Users/muni/.go/src/github.com/munisystem/hoge/docs/accountname.apib
	create /Users/muni/.go/src/github.com/munisystem/hoge/controllers/user.go
	create /Users/muni/.go/src/github.com/munisystem/hoge/controllers/accountname.go
	create /Users/muni/.go/src/github.com/munisystem/hoge/controllers/nation.go
	create /Users/muni/.go/src/github.com/munisystem/hoge/docs/profile.apib
	create /Users/muni/.go/src/github.com/munisystem/hoge/docs/email.apib
	create /Users/muni/.go/src/github.com/munisystem/hoge/controllers/profile.go
	create /Users/muni/.go/src/github.com/munisystem/hoge/controllers/email.go
	create /Users/muni/.go/src/github.com/munisystem/hoge/docs/index.apib
	update /Users/muni/.go/src/github.com/munisystem/hoge/router/router.go
	update /Users/muni/.go/src/github.com/munisystem/hoge/README.md
===> Generated...
```

**Comment by dtan4** [comment]
LGTM 👍

**Pull request merged**
