### PR TITLE
Add utility method for versioning in controllers

### PR DESCRIPTION
**Pull request by munisystem**
## WHY
Based on discussion.

- API supported semantic versioning.
- ``apig`` not generate versioning rogic, but generate utility method.

## WHAT
- Add function of versioning.
- Add utility method for versioning in generated controllers.

### CODE REVIEW

**Comment by dtan4** [comment]
Importing `{{ .ImportDir }}/models` at controller is missing ❗

**Comment by dtan4** [comment]
In `GetModel` function I got the error below:

```
controllers/job.go:44: no new variables on left side of :=
controllers/user.go:44: no new variables on left side of :=
```

template:

https://github.com/wantedly/apig/blob/8fcec7768a240a070839c9201378a9e06263077d/_templates/controller.go.tmpl#L43

How about this patch:

```diff
diff --git a/_templates/controller.go.tmpl b/_templates/controller.go.tmpl
index 682bac9..bade035 100644
--- a/_templates/controller.go.tmpl
+++ b/_templates/controller.go.tmpl
@@ -40,9 +40,8 @@ func Get{{ .Model.Name }}(c *gin.Context) {
 	id := c.Params.ByName("id")
 	fields := c.DefaultQuery("fields", "*")
 	var {{ tolower .Model.Name }} models.{{ .Model.Name }}
-	err := db.Select(fields).First(&{{ tolower .Model.Name }}, id).Error
 
-	if err != nil {
+	if db.Select(fields).First(&{{ tolower .Model.Name }}, id).Error != nil {
 		content := gin.H{"error": "{{ tolower .Model.Name }} with id#" + id + " not found"}
 		c.JSON(404, content)
 		return
```

**Comment by munisystem** [comment]
>Importing {{ .ImportDir }}/models at controller is missing ❗

but ``{{ .ImportDir }}/version`` ?

FIxed. How about?

**Comment by dtan4** [comment]
> but {{ .ImportDir }}/version ?

You're right 😝

**Comment by dtan4** [comment]
LGTM 👍 Thanks ❗

**Pull request merged**
