### PR TITLE
Use mitchellh-cli

### PR DESCRIPTION
**Pull request by munisystem**
## WHY
Close https://github.com/wantedly/apig/issues/35

## WHAT
- Use mitchellh-cli.
- Add same unit test.

## Problem
~~After run `new` command executed.~~
```
>>> bin/apig new -u wantedly testproject
_templates/skeleton/db/pagination.go.tmpl
	create /Users/muni/.go/src/github.com/wantedly/testproject/models/.gitkeep
	create /Users/muni/.go/src/github.com/wantedly/testproject/main.go
	create /Users/muni/.go/src/github.com/wantedly/testproject/db/pagination.go
html/template:complex: "=" in unquoted attr: "%v&last_id=%v&order=%v"
```
~~_template/skeleton/db/pagination.go.tmpl is broken.~~
Fixed (f8f163b)

### CODE REVIEW

**Comment by dtan4** [comment]
Didn't you forget to add `apig` directory? I couldn't build...

```bash
$ make
go get github.com/jteeuwen/go-bindata/...
./glide install
[INFO]  Downloading dependencies. Please wait...
[INFO]  --> Found desired version github.com/gedex/inflector 91797f1712fd58f224781be1080b8613d096187e!
[INFO]  --> Found desired version github.com/tcnksm/go-gitconfig 6411ba19847f20afe47f603328d97aaeca6def6f!
[INFO]  Setting references.
[INFO]  --> Setting version for github.com/gedex/inflector to 91797f1712fd58f224781be1080b8613d096187e.
[INFO]  --> Setting version for github.com/tcnksm/go-gitconfig to 6411ba19847f20afe47f603328d97aaeca6def6f.
go generate
go build -ldflags="-s -w" -o bin/apig
command/gen.go:9:2: cannot find package "github.com/wantedly/apig/apig" in any of:
        /Users/dtan4/src/github.com/wantedly/apig/vendor/github.com/wantedly/apig/apig (vendor tree)
        /usr/local/Cellar/go/1.6.3/libexec/src/github.com/wantedly/apig/apig (from $GOROOT)
        /Users/dtan4/src/github.com/wantedly/apig/apig (from $GOPATH)
make: *** [bin/apig] Error 1
```

**Comment by munisystem** [comment]
@dtan4 Sorry. `/apig` untracked. Fixed d59a464

**Comment by munisystem** [comment]
Fix conflict.

**Comment by dtan4** [comment]
Behavior looks good.

I have two favors for you:
- Execute `./glide get github.com/mitchellh/cli` at the top of repository
- Rewrite script of `make test` as `go test -cover -v ./apig ./command`

**Comment by munisystem** [comment]
@dtan4 Thank you your review and advice. I'll do it as soon as possible.

**Comment by dtan4** [comment]
LGTM 👍

**Pull request merged**
