### PR TITLE
Choose deeply-nested field correctly

### PR DESCRIPTION
**Pull request by dtan4**
## WHY

Generated API server has the feature to choose fields in response by `fields` parameter. Currently there is a limitation of depth to choose nested fields.

For example, response against the request below is expected to include `country` field only. However in reality, server returns both `id` and `country`.

```bash
$ curl -s "localhost:8080/api/users?preloads=profile.nation&fields=profile.nation.country" | jq .
[
  {
    "profile": {
      "nation": {
        "id": 1,
        "country": "japan"
      }
    }
  }
]
```

Another problem is that the logic of parsing `fields` parameter and selecting response fields are so complicated.

## WHAT

Rewrite selector logic to choose fields at any depth.
With this patch, we can receive `country` field only!

```bash
$ curl -s "localhost:8080/api/users?preloads=profile.nation&fields=profile.nation.country" | jq .                                          [
  {
    "profile": {
      "nation": {
        "country": "japan"
      }
    }
  }
]
```

### `ParseFields`

Parse dot-separated string and build a tree of selector.

example: 

```
input: profile.nation.name,profile.id

output:
{
  "profile": {
    "nation": {
      "name": nil,
    },
    "id": nil,
  },
}
```

### `FieldToMap`

Walk the given model object and choose field to include in response from selector tree.

### CODE REVIEW

**Comment by awakia** [comment]
Looks good. However, I think we need some tests for this kind of complex logic. How do you think?

**Comment by dtan4** [comment]
> I think we need some tests for this kind of complex logic.

I think so too actually... That means generated server included test for this logic, doesn't it?

**Comment by awakia** [comment]
why don't we merge first?

**Comment by dtan4** [comment]
okay 👌

**Pull request merged**
