### PR TITLE
Specify namespace with apig gen --all

### PR DESCRIPTION
**Pull request by dtan4**
## WHY
When user executes `apig gen --all` at application repository, API namespace always rewrite as `""` (empty string).

## WHAT
Add `--namespace` option to `apig gen` command, like `apig new` command.

### CODE REVIEW

**Comment by awakia** [comment]
Thank you! But, actually namespace should be parsed by existing template.
I think this is not so difficult. Do you want to merge this?

**Comment by dtan4** [comment]
Okay, I'll create another patch along with your idea. That looks smarter than mine.

**Comment by dtan4** [comment]
I also think that `--namespace` option is still useful if user wants to change API namespace at once. So...

- If `--namespace` option is passed, apig uses the passed value.
- If not, apig tries to parse existing `router.go` and extract namespace from it.

@awakia How do you think about this?

**Comment by awakia** [comment]
I think, vcs and username is not supplied as gen command. If so, just giving namespace is confusing. Another staff is, changing namespace needs to change only one lines of code. That may be useless.

**Comment by dtan4** [comment]
> vcs and username is not supplied as gen command.

> changing namespace needs to change only one lines of code

Thanks, you're right. We no longer need `--namespace` anymore.

I created #58 which implements extracting namespace from `routes.go`, so now I close this. Please take a look of #58.

**Pull request closed without merging**
